export default {
  FETCH_SCHEDULE: "FETCH_SCHEDULE",
  FETCH_SCHEDULE_SUCCESS: "FETCH_SCHEDULE_SUCCESS",
  FETCH_SCHEDULE_FAILED: "FETCH_SCHEDULE_FAILED",
  UPDATE_ASSIGNMENT: "UPDATE_ASSIGNMENT",
  UPDATE_ASSIGNMENT_SUCCESS: "UPDATE_ASSIGNMENT_SUCCESS",
  UPDATE_ASSIGNMENT_FAILED: "UPDATE_ASSIGNMENT_FAILED",
};
